-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 11:14:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema guitare_app
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `guitare_app` ;

-- -----------------------------------------------------
-- Schema guitare_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `guitare_app` DEFAULT CHARACTER SET utf8 ;
USE `guitare_app` ;

-- -----------------------------------------------------
-- Table `guitare_app`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitare_app`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `guitare_app`.`utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nomUtilisateur` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `administrateur` TINYINT NOT NULL,
  `valide` TINYINT NULL,
  `jeton` VARCHAR(225) NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guitare_app`.`favoris`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitare_app`.`favoris` ;

CREATE TABLE IF NOT EXISTS `guitare_app`.`favoris` (
  `idFavoris` INT NOT NULL AUTO_INCREMENT,
  `nomFavoris` VARCHAR(100) NOT NULL,
  `fkIdUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idFavoris`, `fkIdUtilisateur`),
  CONSTRAINT `favoris_fkIdUtilisateur`
    FOREIGN KEY (`fkIdUtilisateur`)
    REFERENCES `guitare_app`.`utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IDX_favoris_fkIdUtilisateur` ON `guitare_app`.`favoris` (`fkIdUtilisateur` ASC);


-- -----------------------------------------------------
-- Table `guitare_app`.`guitare`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitare_app`.`guitare` ;

CREATE TABLE IF NOT EXISTS `guitare_app`.`guitare` (
  `idGuitare` INT NOT NULL AUTO_INCREMENT,
  `nomGuitare` VARCHAR(100) NOT NULL,
  `prix` SMALLINT NULL,
  `nbCordes` TINYINT NULL,
  `description` TEXT NULL,
  `cheminPhoto` TEXT NULL,
  `dateFab` YEAR NULL,
  `etui` TINYINT NULL,
  PRIMARY KEY (`idGuitare`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guitare_app`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitare_app`.`genre` ;

CREATE TABLE IF NOT EXISTS `guitare_app`.`genre` (
  `idGenre` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guitare_app`.`guitare_genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitare_app`.`guitare_genre` ;

CREATE TABLE IF NOT EXISTS `guitare_app`.`guitare_genre` (
  `idGuitareGenre` INT NOT NULL AUTO_INCREMENT,
  `fkIdGuitare` INT NOT NULL,
  `fkIdGenre` INT NOT NULL,
  PRIMARY KEY (`idGuitareGenre`, `fkIdGuitare`, `fkIdGenre`),
  CONSTRAINT `guitare_genre_fkIdGuitare`
    FOREIGN KEY (`fkIdGuitare`)
    REFERENCES `guitare_app`.`guitare` (`idGuitare`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `guitare_genre_fkIdGenre`
    FOREIGN KEY (`fkIdGenre`)
    REFERENCES `guitare_app`.`genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IDX_guitare_genre_fkIdGuitare` ON `guitare_app`.`guitare_genre` (`fkIdGuitare` ASC);

CREATE INDEX `IDX_guitare_genre_fkIdGenre` ON `guitare_app`.`guitare_genre` (`fkIdGenre` ASC);


-- -----------------------------------------------------
-- Table `guitare_app`.`finition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitare_app`.`finition` ;

CREATE TABLE IF NOT EXISTS `guitare_app`.`finition` (
  `idFinition` INT NOT NULL AUTO_INCREMENT,
  `finition` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idFinition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guitare_app`.`guitare_finition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitare_app`.`guitare_finition` ;

CREATE TABLE IF NOT EXISTS `guitare_app`.`guitare_finition` (
  `IdGuitareFinition` INT NOT NULL AUTO_INCREMENT,
  `fkIdGuitare` INT NOT NULL,
  `fkIdFinition` INT NOT NULL,
  PRIMARY KEY (`IdGuitareFinition`, `fkIdGuitare`, `fkIdFinition`),
  CONSTRAINT `guitare_finition_fkIdGuitare`
    FOREIGN KEY (`fkIdGuitare`)
    REFERENCES `guitare_app`.`guitare` (`idGuitare`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `guitare_finition_fkIdFinition`
    FOREIGN KEY (`fkIdFinition`)
    REFERENCES `guitare_app`.`finition` (`idFinition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IDX_guitare_finition_fkIdGuitare` ON `guitare_app`.`guitare_finition` (`fkIdGuitare` ASC);

CREATE INDEX `IDX_guitare_finition_fkIdFinition` ON `guitare_app`.`guitare_finition` (`fkIdFinition` ASC);


-- -----------------------------------------------------
-- Table `guitare_app`.`modele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitare_app`.`modele` ;

CREATE TABLE IF NOT EXISTS `guitare_app`.`modele` (
  `idModele` INT NOT NULL AUTO_INCREMENT,
  `modele` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idModele`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guitare_app`.`guitare_modele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitare_app`.`guitare_modele` ;

CREATE TABLE IF NOT EXISTS `guitare_app`.`guitare_modele` (
  `idGuitareModele` INT NOT NULL AUTO_INCREMENT,
  `fkIdGuitare` INT NOT NULL,
  `fkIdModele` INT NOT NULL,
  PRIMARY KEY (`idGuitareModele`, `fkIdGuitare`, `fkIdModele`),
  CONSTRAINT `guitare_model_fkIdGuitare`
    FOREIGN KEY (`fkIdGuitare`)
    REFERENCES `guitare_app`.`guitare` (`idGuitare`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `guitare_mode_fkIdModel`
    FOREIGN KEY (`fkIdModele`)
    REFERENCES `guitare_app`.`modele` (`idModele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IDX_guitare_modele_fkIdGuitare` ON `guitare_app`.`guitare_modele` (`fkIdGuitare` ASC);

CREATE INDEX `IDX_guitare_modele_fkIdModele` ON `guitare_app`.`guitare_modele` (`fkIdModele` ASC);


-- -----------------------------------------------------
-- Table `guitare_app`.`favoris_guitare`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitare_app`.`favoris_guitare` ;

CREATE TABLE IF NOT EXISTS `guitare_app`.`favoris_guitare` (
  `idFavorisGuitare` INT NOT NULL AUTO_INCREMENT,
  `fkIdFavoris` INT NOT NULL,
  `fkIdGuitare` INT NOT NULL,
  PRIMARY KEY (`idFavorisGuitare`, `fkIdFavoris`, `fkIdGuitare`),
  CONSTRAINT `favoris_guitare_fkIdFavoris`
    FOREIGN KEY (`fkIdFavoris`)
    REFERENCES `guitare_app`.`favoris` (`idFavoris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `favoris_guitare_fkIdGuitare`
    FOREIGN KEY (`fkIdGuitare`)
    REFERENCES `guitare_app`.`guitare` (`idGuitare`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IDX_favoris_guitare_fkIdFavoris` ON `guitare_app`.`favoris_guitare` (`fkIdFavoris` ASC);

CREATE INDEX `IDX_favoris_guitare_fkIdGuitare` ON `guitare_app`.`favoris_guitare` (`fkIdGuitare` ASC);


-- -----------------------------------------------------
-- Table `guitare_app`.`marque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitare_app`.`marque` ;

CREATE TABLE IF NOT EXISTS `guitare_app`.`marque` (
  `idMarque` INT NOT NULL AUTO_INCREMENT,
  `nom_marque` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idMarque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guitare_app`.`guitare_marque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guitare_app`.`guitare_marque` ;

CREATE TABLE IF NOT EXISTS `guitare_app`.`guitare_marque` (
  `idGuitareMarque` INT NOT NULL AUTO_INCREMENT,
  `fkIdGuitare` INT NOT NULL,
  `fkIdMarque` INT NOT NULL,
  PRIMARY KEY (`idGuitareMarque`, `fkIdGuitare`, `fkIdMarque`),
  CONSTRAINT `guitare_marque_fkIdGuitare`
    FOREIGN KEY (`fkIdGuitare`)
    REFERENCES `guitare_app`.`guitare` (`idGuitare`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `guitare_marque_fkIdMarque`
    FOREIGN KEY (`fkIdMarque`)
    REFERENCES `guitare_app`.`marque` (`idMarque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IDX_guitare_marque_fkIdGuitare` ON `guitare_app`.`guitare_marque` (`fkIdGuitare` ASC);

CREATE INDEX `IDX_guitare_marque_fkIdMarque` ON `guitare_app`.`guitare_marque` (`fkIdMarque` ASC);

-- -----------------------------------------------------

-- Table `guitare_app`.`message`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `guitare_app`.`message` (

`idMessage` INT NOT NULL AUTO_INCREMENT,

`content` MEDIUMTEXT NOT NULL,

`dateEnvoie` DATE NOT NULL,

`subject` VARCHAR(100) NOT NULL,

PRIMARY KEY (`idMessage`))

ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
